language: objective-c
osx_image: xcode8
before_install:
  - gem install xcov --no-ri --no-rdoc --no-document
  - gem install fastlane --no-ri --no-rdoc --no-document
script: travis/script.sh
after_success: travis/after_success_script.sh
